(function(){this._ila=this._ila||{};(function(_){var window=this;try{var ba,da,ca,F;ba=this;da=function(a){var b=typeof a;if("object"==b)
if(a){if(a instanceof Array)return "array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return "object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return "array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return "function"}else return "null";else if("function"==b&&"undefined"==typeof a.call)return "object";return b};ca=function(a,b){var c=a.split("."),d=ba;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b};F=function(a,b){C.prototype[a]=b};_.G=function(a,b){function c(){}
c.prototype=b.prototype;a.Ka=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Fa=function(a,c,f){for(var m=Array(arguments.length-2),n=2;n<arguments.length;n++)m[n-2]=arguments[n];return b.prototype[c].apply(a,m)}};var ea=function(){};var qb=function(a){return-1!=jb.indexOf(a)},fa=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};var ga,J,na;_.M=function(a,b){if(!J){J={};var c=window.document.getElementById("isr_param");if(c)
for(var d=0;d<c.attributes.length;++d){var e=c.attributes[d];0==e.name.indexOf("data-")&&(J[e.name]=e.value)}}
return J.hasOwnProperty(a)?(0,window.parseFloat)(J[a]):b};_.N=_.M("data-ma",12);_.ia=_.M("data-mrw",80);_.O=1+_.M("data-isuf",0);_.P=function(a,b){return a?(new RegExp("(\\s|^)"+b+"(\\s|$)")).test(a.className):!1};_.ja=function(a){return window.JSON?window.JSON.parse(a):eval("("+a+")")};_.Q=function(a,b){if(void 0===ga){var c=window.google.ua||window.navigator.userAgent;ga=!(!c||-1==c.indexOf("WebKit")||0==c.indexOf("Opera"))}
if(ga)
for(var d in b)c=fa(d),a.style[c]=b[d];else{c=[];for(d in b)c.push(d+":"+b[d]);a.setAttribute("style",c.join(";"))}};_.ha=function(a){for(var b=[],c=0,d;d=a.childNodes[c];c++)1==d.nodeType&&_.P(d,"rg_di")&&b.push(d);return b};_.ka=function(a,b){this.o=a;this.ra="1"==b.bc;this.va=(0,window.parseInt)(b.ct,10)||0;this.wa=(0,window.parseInt)(b.cb,10)||0;this.ta=(0,window.parseInt)(b.cl,10)||0;this.V=(0,window.parseInt)(b.cr,10)||0;this.ya="1"==b.sc;this.width=b.tw;this.height=b.th;this.Ha=1==b.ps};na=_.M("data-eca",.1);_.R=function(a){return a.width/a.height};_.oa=function(a){if(a.ra)return _.R(a);var b=(a.ta+a.V)/100;a.ya||(b=Math.min(1,b+na));return(a.width-a.width*b)/a.height};_.pa=function(a){if(a.ra)return _.R(a);var b=(a.va+a.wa)/100;a.ya||(b=Math.min(1,b+na));return a.width/(a.height-a.height*b)};_.qa=function(a,b){return 0==a.va&&0==a.wa?Math.floor(.5*b):Math.round(a.va/(a.va+a.wa)*b)};_.ra=function(a,b){return 0==a.ta&&0==a.V?Math.floor(b/2):Math.round(a.ta/(a.ta+a.V)*b)};var sa=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e=d,f=da(e);if("array"==f||"object"==f&&"number"==typeof e.length){e=a.length||0;f=d.length||0;a.length=e+f;for(var m=0;m<f;m++)a[e+m]=d[m]}else a.push(d)}};var jb;a:{var ma=ba.navigator;if(ma){var Aa=ma.userAgent;if(Aa){jb=Aa;break a}}
jb=""};var Ja=function(){return qb("Android")&&!((qb("Chrome")||qb("CriOS"))&&!qb("Opera")&&!qb("OPR")&&!qb("Edge")||qb("Firefox")||qb("Opera")||qb("OPR")||qb("Silk"))};var mb;mb={};_.nb=function(){if(Ja()&&0<window.outerHeight&&window.innerHeight>window.outerHeight){var a=window.outerWidth;if(mb[a])return mb[a];mb[a]=window.innerWidth}
return window.innerWidth||window.document.documentElement.offsetWidth};var ta,wa,ua,va,xa;ta=function(){};_.S=function(a){var b=_.W;a.Ka||_.G(a,b);a.Xa=0;if(b.$){for(var b=b.$,c=0,d=b.length-1;c<=d;){var e=c+d>>1;0>b[e].Xa?d=e-1:c=e+1}
c<b.length&&0==b[c].Xa&&++c;b.splice(c,0,a)}else b.$=[a]};wa=function(a){var b=a.La,c=function(a){c.Ka.constructor.call(this,a);var b=this.$.length;this.ta=[];for(var d=0;d<b;++d)this.$[d].Ga||(this.ta[d]=new this.$[d](a))};_.G(c,b);for(var d=[];a;){if(b=a.La){b.$&&sa(d,b.$);var e=b.prototype,f;for(f in e)
if(e.hasOwnProperty(f)&&"function"==da(e[f])&&e[f]!==b){var m=!!e[f].Da,n=ua(f,e,d,m);(m=va(f,e,n,m))&&(c.prototype[f]=m)}}
a=a.Ka&&a.Ka.constructor}
c.prototype.$=d;return c};ua=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),!d));++f);return e};va=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.ta[c[0]];return d?d[a].apply(this.ta[c[0]],arguments):this.$[c[0]].prototype[a].apply(this,arguments)}:b[a].Ea?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var g=this.ta[c[e]];if(g=g?g[a].apply(g,d):this.$[c[e]].prototype[a].apply(this,d)){d=g;break a}}
d=!1}
return d}:b[a].Va?e=function(b){var d;a:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var g=this.ta[c[e]],g=g?g[a].apply(g,d):this.$[c[e]].prototype[a].apply(this,d);if(null!=g){d=g;break a}}
d=void 0}
return d}:b[a].ma?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var g=this.ta[c[e]];g?g[a].apply(g,d):this.$[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],g=0;g<c.length;++g){var k=this.ta[c[g]];e.push(k?k[a].apply(k,d):this.$[c[g]].prototype[a].apply(this,d))}
return e}:d||b[a].Ea||b[a].Va||b[a].ma?e=null:e=xa;return e};xa=function(){return[]};ta.prototype.Ba=function(a){if(this.ta)
for(var b=0;b<this.ta.length;++b)
if(this.ta[b]instanceof a)return this.ta[b];return null};var ya=function(){var a=function(){};a.Va=!0;return a},T=function(){var a=function(){};a.Da=!0;return a},V=function(){var a=function(){};a.ma=!0;return a};var za=function(a){return this.qa.Ba(a)};var C=function(){if(!this.qa){for(var a=this.constructor;a&&!a.La;)a=a.Ka&&a.Ka.constructor;a.La.Ya||(a.La.Ya=wa(a));this.qa=new a.La.Ya(this);this.Ba||(this.Ba=za)}
this.ra=new ea;this.o=[];this.rb=[];this.yb=[];this.Ha=[];this.wb=!1;this.wa=_.M("data-cs",100)},U,Ua;C.prototype.V=!1;C.prototype.Fb=0;C.prototype.Ib=function(){return this.wa};F("fullChunkSize",C.prototype.Ib);C.prototype.getResults=function(){return this.yb};F("getResults",C.prototype.getResults);C.prototype.Ab=function(){return this.qa.Za()};F("getNumPages",C.prototype.Ab);C.prototype.Bb=function(a){return this.qa.$a(a)};F("getResultsForPage",C.prototype.Bb);C.prototype.ya=function(a){this.Aa=this.o.length?a?2:1:0;this.ta=window.document.getElementById("rg_s");switch(this.Aa){case 0:this.qa.Ua();this.qa.Sa();this.qa.na();Ca(this);Ba(this);Ea(this);break;case 1:this.qa.oa(this.va);this.qa.ub(this.Aa,this.ra,this.va);break;case 2:this.qa.Sa();this.yb=[];Ca(this);this.qa.Wa();Ea(this);break;default:throw Error("b`"+this.Aa);}};F("layoutResults",C.prototype.ya);C.prototype.Db=function(){var a=window.document.getElementById("rg_s"),b=window.document.querySelectorAll("div.rg_add_chunk"),c=[];if(a&&0!=b.length){for(var d,e=0;d=b[e];++e){var f=d.getAttribute("data-cei");f||window.google.ml(Error("c"),!1);if(f&&!this.rb[f]){this.rb[f]=!0;var m=1==this.o.length&&this.o[0]<this.wa,n=3==this.o.length;m?function(){var a={time:window.google.time()};window.google.load("str",function(){window.google.isr.csi.cl1s(null,a)})}():n&&function(){var a={time:window.google.time()};window.google.load("str",function(){window.google.isr.csi.cl3s(null,a)})}();for(this.va=window.document.createDocumentFragment();0<d.childNodes.length;)this.va.appendChild(d.childNodes[0]);sa(c,_.ha(this.va));this.ya();a.appendChild(this.va);this.va=null}
d.parentNode.removeChild(d);m?function(){var a={time:window.google.time()};window.google.load("str",function(){window.google.isr.csi.cl1e(null,a)})}():n&&function(){var a={time:window.google.time()};window.google.load("str",function(){window.google.isr.csi.cl3e(null,a)})}()}
_.Fa(this,c)}else 1==this.o.length&&20>=this.o[0]&&this.Na()};F("moveAndLayoutNewResults",C.prototype.Db);_.Fa=function(a,b){for(var c=0;c<a.Ha.length;++c)try{a.Ha[c](b)}catch(d){}};C.prototype.Na=function(){this.V=!0;this.qa.kb()};F("setAllResultsLoaded",C.prototype.Na);C.prototype.Hb=function(){return this.V};F("areAllResultsLoaded",C.prototype.Hb);C.prototype.Lb=function(a){return this.o[a]||0};F("getChunkSize",C.prototype.Lb);C.prototype.Cb=function(a){return void 0!==this.o[a]};F("hasRenderedChunk",C.prototype.Cb);C.prototype.Mb=function(){return this.o};F("getChunkSizeArray",C.prototype.Mb);var Ca=function(a){var b=a.ra,c;a:{if(Ja()&&0<window.outerHeight&&window.innerHeight>window.outerHeight){c=window.outerHeight;var d=window.innerHeight;d<2*c&&(mb[c]=d);if(mb[c]){c=mb[c];break a}}
c=window.innerHeight||window.document.documentElement.offsetHeight}
b=b.Ja=c;a.ra.va=_.nb();c=a.ta;for(d=0;c&&!(0,window.isNaN)(c.offsetTop);)d+=c.offsetTop,c=c.offsetParent;c=a.ra.ta=d;a.ra.ra=b-c;b=window.document.getElementById("rso").offsetWidth;0<b&&(a.ra.o=b+_.N);window.document.getElementById("rg").style.width=(a.ra.o||0)+"px"},Ea=function(a){var b=a.ta.parentNode,c=a.ta.nextSibling;b.removeChild(a.ta);a.qa.ka(a.Aa,a.ra,a.va);a.ta.style.visibility="inherit";b.insertBefore(a.ta,c)},Ba=function(a){var b={num:Da(a)};window.google.load("str",function(){window.google.isr.csi.ni(null,b)})};C.prototype.Jb=function(){return this.ra.Ja};F("getCachedViewportHeight",C.prototype.Jb);C.prototype.Kb=function(){return this.ra.va};F("getCachedViewportWidth",C.prototype.Kb);var Da=function(a){a=a.ta.getElementsByTagName("img");for(var b=0,c;(c=a[b])&&!(c.hasAttribute("data-src")||c.hasAttribute("src")&&0!=c.getAttribute("src").indexOf("data:"));b++);return b};C.prototype.Gb=function(a){this.Ha.push(a)};F("addNewResultsListener",C.prototype.Gb);C.prototype.Eb=function(a){var b=this.Ha,c=-1;if(Array.prototype.indexOf)c=Array.prototype.indexOf.call(b,a);else
for(var d=b.length,e=0;e<d;e++)
if(b[e]===a){c=e;break}
a=c;-1!=a&&b.splice(a,1)};F("removeNewResultsListener",C.prototype.Eb);_.W=function(a){this.ra=a};U=_.W;Ua=C;U.Ka||_.G(U,ta);Ua.La=U;_.A=_.W.prototype;_.A.Za=ya();_.A.$a=ya();_.A.kb=V();_.A.Ua=V();_.A.Sa=V();_.A.na=T();_.A.oa=T();_.A.ka=T();_.A.ub=T();_.A.Wa=V();ca("google.isr.layoutInit",function(){(function(){var a={time:window.google.time()};window.google.load("str",function(){window.google.isr.csi.cl0s(null,a)})})();var a=new C;a.ya();(function(){var a={time:window.google.time()};window.google.load("str",function(){window.google.isr.csi.cl0e(null,a)})})();ca("google.isr.layout",a)});_.Ha=function(a,b,c,d,e,f,m,n,g){var k=[];if(!a.length)return k;var p=b-c,Ga=[],y=0;if(0>p)
for(c=0;c<a.length;c++){var q=a[c],r=_.X(q,d,f,m),q=r/_.R(q)*(_.oa(q)-_.R(q));if(0<q)throw Error("f");q+r<f&&(q=f-r);Ga[c]=q;y+=q}else if(!g)
for(c=0;c<a.length;c++){q=a[c];q=_.Y(_.pa(q),d,f,q.width,m)-_.X(q,d,f,m);if(0>q)throw Error("g");Ga[c]=q;y+=q}
for(c=q=0;c<a.length;c++)r=Math.round(Math.max(f,_.X(a[c],d,f,m)+(g||0==y?0:p*Ga[c]/y))),q+=r+e,k.push(r);if(!g)
if(b=b-q-(n||0),k[k.length-1]+b<f)
for(c=k.length-
1;-1<c&&(a=Math.max(b,f-k[c]),k[c]+=a,b-=a,0!=b);c--);else a[a.length-1].Ha&&0<b||(k[k.length-1]+=b);return k};_.X=function(a,b,c,d){return _.Y(_.R(a),b,c,a.width,d)};_.Y=function(a,b,c,d,e){return Math.max(Math.min(b*Math.min(a,e||Number.MAX_VALUE),d),c)};var Va=function(a){window.google.log("ispo","&start=0&ndsp="+a);var b={size:a};window.google.load("str",function(){window.google.isr.csi.fps(null,b)})},Wa=function(a){if(!a.o.length)return!1;if(a.wb)return a.o[a.o.length-1]<a.wa;switch(a.o.length){case 1:return 20>a.o[0];case 2:return a.o[1]<a.wa-20;default:return a.o[a.o.length-1]<a.wa}},Xa=function(a,b){b.hasAttribute("data-ri")||b.setAttribute("data-ri",a.Fb++)},Za=function(a){this.ra=a;this.wa=window.document.getElementById("rg_s");this.o=[];a=window.document.getElementById("isr_spnm");this.Ha=!!a;this.Aa=a?a.innerHTML:"";this.ya=this.V=0};_.G(Za,_.W);_.S(Za);_.Z=function(){return{results:[],o:0,ra:0}};_.A=Za.prototype;_.A.Za=function(){return this.o.length};_.A.$a=function(a){return(a=this.o[a])?a.results:null};_.A.kb=function(){if(this.va&&this.va.length){var a;a=this.va;var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];a=c}else a=[];this.ra.ya();_.Fa(this.ra,a)}};_.A.Sa=function(){for(var a=0,b;b=this.wa.children[a];a++)_.P(b,"rgsh")&&(this.wa.removeChild(b),a--)};_.A.na=function(){for(var a=this.ra.o,b=0,c=this.wa.children,d=0,e;e=c[d];d++)pb(e)&&(Xa(this.ra,e),e.hasAttribute("data-ci")&&(a.push(b),b=0),b++);0<b&&(a.push(b),Wa(this.ra)&&this.ra.Na())};_.A.oa=function(a){if(a){a=_.ha(a);for(var b=0,c;c=a[b];b++)Xa(this.ra,c);b=this.ra;c=a.length;if(0<c){var d=b.o.length;1==d&&b.o[0]<b.wa?(b.o[0]+=c,b.wb=!0):(a[0].setAttribute("data-ci",d),b.o.push(c))}
Wa(b)&&(b.V=!0)}};_.A.ka=function(a,b,c){for(var d=[],e=this.wa.children,f=0,m;m=e[f];f++)pb(m)&&d.push(m);if(c)
for(c=c.childNodes,f=0;e=c[f];f++)pb(e)&&d.push(e);0<d.length&&$a(this,a,b,d)};_.A.ub=function(a,b,c){var d=[],e=null;if(this.va&&this.va.length)
for(var f=window.document.createDocumentFragment(),m=0;m<this.va.length;m++){for(var n=this.va[m],e=[],g=n.previousSibling;g&&8==g.nodeType;)e.push(g),g=g.previousSibling;for(;g=e.pop();)f.appendChild(g);e=n.nextSibling;for(f.appendChild(n);e&&8==e.nodeType;)g=e,e=g.nextSibling,f.appendChild(g);d.push(n)}
if(c)
for(c=c.childNodes,m=0;n=c[m];m++)pb(n)&&d.push(n);$a(this,a,b,d);f&&this.wa.insertBefore(f,e)};_.A.Wa=function(){this.o=[];this.va=[];this.ya=this.V=0};var $a=function(a,b,c,d){for(var e,f,m=[],n=0;n<d.length;n++){for(var g=n,k=d[n],p=void 0,Ga=k.getElementsByTagName("div"),y=0,q=void 0;q=Ga[y];y++)
if("rg_meta"==q.className){p=_.ja(q.innerText||q.textContent||q.innerHTML);break}
if(!p)throw window.google.ml(Error("d"),!1,{url:window.location.href}),Error("e");m[g]=new _.ka(k,p)}
if(c.o&&(n=_.Z(m,c,!a.ra.V))){k=g=0;a.o.length||a.o.push({results:[],Ca:0});p=a.o[a.o.length-1];Ga=1==a.o.length?c.ra:c.Ja;y=a.Ha?32:0;for(q=0;q<n.o.length;q++){if(0!=p.Ca&&Ga-p.Ca<=y){a.V+=p.Ca;p={results:[],Ca:0};a.o.push(p);var Ga=c.Ja,r=window.document.createElement("div");r.className="rgsh";a.Ha?r.innerHTML=a.Aa.replace(/\%1\$d/,String(a.o.length)):r.style.display="none";r.setAttribute("id","page"+a.o.length);r.setAttribute("data-pg",a.o.length);r.setAttribute("data-offset",c.ta+a.V+p.Ca);r.setAttribute("data-fri",a.ra.getResults().length);for(var u=d[k];u.previousSibling&&8==u.previousSibling.nodeType&&"n"!=u.previousSibling.nodeValue;)u=u.previousSibling;u.parentNode.insertBefore(r,u);a.Ha&&(p.Ca+=32);2!=b&&2==a.o.length&&Va(a.o[0].results.length)}
p.Ca+=n.ra[q];p.Ca+=_.N;for(r=0;r<n.o[q];r++){f=n.results[g];var h=u=m[k],l=f.width;e=f.height;f={Ma:0,Pa:0,ob:0,pb:0,nb:0,N:0,T:0,Oa:0,lb:0,mb:0,vb:0,Qa:0};f.Ma=l;f.Pa=e;f.Qa=e;f.N=h.width;f.T=h.height;if(h.width>l||h.height>e){var x=l/e,z=Math.min(_.pa(h),Math.max(x,_.oa(h)));_.R(h)>z?(x=Math.min(h.height,l/z),f.N=x*_.R(h),f.T=x):(x=Math.min(h.width,z>x?l:e*z),f.N=x,f.T=x/_.R(h))}
1<_.O&&!h.ra&&((z=Math.min(l/f.N,_.O),x=Math.min(e/f.T,_.O),1<z)?(x=Math.max(x,z),f.N*=x,f.T*=x):1<x&&(z=f.N*x,z>l||z*_.O<l)&&(f.T*=x,f.N=z));f.N=Math.round(f.N);f.T=Math.round(f.T);f.N>l?(x=f.N-l,f.Oa=-1*_.ra(h,f.N-l),f.lb=-x-f.Oa):f.N<l&&(f.ob=(l-f.N)/2);f.T>e?f.mb=-1*_.qa(h,f.T-e):f.T<e&&(f.Qa=f.T,f.Pa=f.T,l=e-f.T,f.pb=Math.floor(l/2),f.nb=Math.ceil(l/2));f.vb=Math.min(f.N,f.Ma);l=f;h=h.o;f=h.getElementsByTagName("img")[0];_.Q(h,{width:l.Ma+"px",height:l.Pa+"px","padding-top":l.pb+"px","padding-bottom":l.nb+"px"});_.Q(f,{width:l.N+"px",height:l.T+
"px","margin-left":l.Oa+"px","margin-right":l.lb+"px","margin-top":l.mb+"px"});e=l.Ma;x=l.N;f=z="";var w=!1;if(x<e){var B=h.getElementsByTagName("div");if(B&&B.length)
for(var t=0,v=void 0;v=B[t];++t)
if("rg_anbg"==v.className){x<_.ia&&(f=(e-_.ia)/2+"px",w=!0);break}}
w||(z=l.ob+"px");e=z;_.Q(h.getElementsByTagName("a")[0],{width:l.vb+"px",height:l.Qa+"px",left:e,right:f});p.results.push(u.o);u.o.setAttribute("data-row",a.ya);a.ra.getResults().push(u.o);(h=u.o.querySelector(".col-badge"))&&_.Q(h,{top:u.o.style.paddingTop,left:u.o.querySelector("a").style.left});u.o.style.display="inline-block";k++;g++}
a.ya++}
a.va=[];for(c=k;c<d.length;c++)d[c].style.display="none",a.va.push(d[c]);a.ra.V&&1==a.o.length&&2!=b&&Va(a.o[0].results.length)}},pb=function(a){return 1==a.nodeType&&_.P(a,"rg_di")};var Ia=function(a,b){this.ta=a;this.o=_.N;this.va=!!b;this.ra=_.ia||0};_.Z=function(a,b,c){var d=Math.min(_.M("data-th",140),Math.floor(b.o/4));c=new Ia(d,c);var e;b=b.o;var f=Number.MAX_VALUE,d=[];e=a.slice(0);var m=c.ta,n=[],g=[];for(a=0;4>a;a++){for(var g=c,k=e,p=b,Ga=f,y=m,q=n,r=d,u=0,h=[],l=[],x=0,z=q.length||Ga/y,w=0;w<z;w++){for(var B=r[w]||0,t=q[w]||y,v=p-B,D=Math.floor(v/(g.o+g.ra)),E=0,H=0,I=0,K=0,la=0;u<k.length&&K<D;){var aa=k[u],L=E+_.X(aa,t,g.ra,2)+g.o,H=H+(_.Y(_.oa(aa),t,g.ra,aa.width,2)+g.o);if(L>v&&L-v>v-E)
if(I>=v)break;else if(H>v)break;K++;E=L;I+=_.Y(_.pa(aa),t,g.ra,aa.width,2)+g.o;la+=_.R(aa);u++;if(E>v)break}
if(0==K&&!B)break;h[w]={count:K,width:E+B,height:t,O:void 0};B=1/Math.sqrt((la+.1)/(K+.1));l.push(B);x+=B}
k=l.length;k<z&&(Ga=k*(y+g.o));y=Ga-g.o*k;for(w=z=0;w<k;w++)p=Math.round(l[w]/x*y),h[w].O=p,z+=p+g.o;0<h.length&&(h[h.length-1].O+=Ga-z);g=h;g.length!=n.length&&(n.length=g.length,f=n.length*(m+c.o));Ga=!1;for(h=0;h<g.length;h++)n[h]!=g[h].O&&(n[h]=g[h].O,Ga=!0);if(!Ga)break}
f=e;a=g;e=0;m=[];n=[];g=[];for(Ga=0;Ga<a.length;Ga++){h=a[Ga];if(!h.count)break;l=b-h.width;if((l=e+h.count==f.length&&l>h.width/h.count)&&c.va)break;l=_.Ha(f.slice(e,e+h.count),b,h.width,h.height,c.o,c.ra,2,d[Ga],l);for(x=0;x<l.length;x++)g.push({width:l[x],height:h.height});e+=h.count;m.push(h.count);n.push(h.height)}
return{results:g,o:m,ra:n}};var Ka=function(a,b){var c=a.parentNode,d=a.nextSibling,e=a.style,f=e.display,m=e.visibility,n=e.position;e.display="inline";e.visibility="hidden";e.position="absolute";window.document.documentElement.appendChild(a);var g=b.call();e.display=f;e.visibility=m;e.position=n;c?c.insertBefore(a,d):window.document.documentElement.removeChild(a);return g};var La=function(a,b,c){this.ta=void 0!==c?c:1;this.o=b;this.ra=a},Ma=function(a,b,c,d){var e={width:b,height:c,Ra:a.length},f=[],m=c-0,n=[],g=0;d&&(b+=1);for(var k=0;k<a.length;k++){var p=_.X(a[k],m,0);n.push(p);g+=p;g+=1}
b=n=_.Ha(a,b,g,m,1,0);for(n=0;n<a.length;n++)g=n==a.length-1,f.push({width:b[n],height:m,U:!0,Ta:d&&g});return{results:f,Ia:[e],R:c}},Na=function(a,b,c,d){for(var e=a.length,f=Math.round((c+1)/e)-1,m=c-(e-1)*(1+f),e={width:b,height:c,Ra:e},n=[],g=0;g<a.length;g++){var k=g==a.length-1;n.push({width:b-(d?0:1),height:k?m:f,U:k,Ta:d})}
return{results:n,Ia:[e],R:c}},Oa=function(a,b,c){for(var d=0,e=0;e<a.length;++e)d+=_.X(a[e],b,0),d+=1;c&&--d;return d};var Qa=function(a,b){this.ta=a;this.o=null;this.ra=[];this.va=1;this.wa=!b;for(var c=this.ta.children,d=0,e;e=c[d];d++)
if(_.P(e,"rg_bb_i")){this.o=e;break}
if(this.o)
for(d=c=this.o.firstChild;d;d=c)
if(c=d.nextSibling,_.P(d,"rg_di"))this.ra.push(Pa(d));else if(_.P(d,"rg_bb_layout")){for(;d.hasChildNodes();)e=d.firstChild,_.P(e,"rg_di")&&this.ra.push(Pa(e)),this.o.insertBefore(e,c);this.o.removeChild(d)}},Pa=function(a){var b;a:{b=a.getElementsByTagName("div");for(var c=0,d;d=b[c];c++)
if("rg_meta"==d.className){b=_.ja(d.innerText||d.textContent||d.innerHTML);break a}
b=null}
if(!b)throw Error("e");return new Ra(a,b)},Sa=function(a){for(var b=a.ta.children,c=0,d;d=b[c];c++)
if("rg_bb_label"==d.className)return b=a.ta,_.P(a.ta.parentElement,"rg_bb_c")&&(b=a.ta.parentNode),Ka(b,function(){return d.offsetHeight});return 0},Ra=function(a,b){_.ka.call(this,a,b);this.width=b.tw;this.height=b.th};_.G(Ra,_.ka);var Ta=function(a){this.ra=a};_.G(Ta,_.W);_.S(Ta);Ta.prototype.Ua=function(){var a=window.document.getElementById("ifb");if(a){var b;b=window.document.getElementById("ifbc");b=(0,window.parseInt)(b.getAttribute("data-h"),10)-8;var c=a.parentNode,d=a.nextSibling;c.removeChild(a);for(var e=a.querySelectorAll("div.rg_fb"),f=0,m=_.nb(),n=!!window.document.getElementById("ifbc").getAttribute("data-o"),g=0,k;k=e[g];g++){var p=new Qa(k,n);p.va=Math.max(1,p.ra.length-2);var Ga,y=b;p.wa&&(y-=30);Ga=p.ra;var y=y-2,q=p.va;if(0==Ga.length)Ga=0;else if(1==Ga.length)Ga=Math.floor(_.X(Ga[0],y,0));else if(2==Ga.length)Ga=Math.floor(_.X(Ga[0],y,0)+_.X(Ga[1],y,0)+1);else{for(var q=Math.max(0,Math.min(void 0!==q?q:1,Ga.length-2)),r=Oa(Ga.slice(0,q),y,q==Ga.length),u=Math.floor((Ga.length-q)/2),h=0,l=q;l<Ga.length;l++)h+=_.R(Ga[l]);Ga=Math.floor(r+h/(Ga.length-q)*u*(y-1)/2+1*(u-1))}
Ga+=2;_.Q(k,{width:Ga-2+"px",height:b-2+"px"});k=p;q=Ga;y=b;k.wa&&(p=Sa(k),y-=p);(p=window.document.documentElement.getAttribute("dir"))||(p=window.document.body.getAttribute("dir"));p="rtl"==p;y=y-0-2;q-=2;h=new La(q,y,k.va);u=k.ra;if(u.length)
if(1==u.length)r=h.ra,h=h.o,u=Math.min(h,u[0].height),r={results:[{width:r,height:u,U:!0,Ta:!0}],R:u,Ia:[{width:r,height:h,Ra:1}]};else if(2==u.length)r=Ma(u,h.ra,h.o,!0);else{var r=u,x=h.ra,u=h.o,h=Math.max(0,Math.min(h.ta,r.length-2)),z=Oa(r.slice(0,h),u,h==r.length);1==h&&(z=Math.min(z,Math.floor(.75*x)));for(var w=Math.floor(.9*Math.min(Math.floor(x/2),Math.floor(u/3))),B=r.length-h,l=0,t=h;t<r.length;t++)l+=_.R(r[t]);l/=B;1>l&&(w=Math.floor(w*l));var t=l=0,v=2;do t=Math.floor(B/v),z=Math.min(x-t*w,z),z=Math.max(w,z),l=Math.round((x-z+1)/t)-1,z=x-(t*(l+1)-1);while(l<w&&v<B&&z>w&&v++);x=Ma(r.slice(0,h),z,u,h==r.length);z=r.length;0!=B%v&&(z-=v+B%v);for(B=0;h<z;h+=v)B++,w=B==t,w=Na(r.slice(h,h+v),l+(w?0:1),u,w),x.results.push.apply(x.results,w.results),x.Ia.push(w.Ia[0]);z<r.length&&(w=Na(r.slice(h),l,u,!0),x.results.push.apply(x.results,w.results),x.Ia.push(w.Ia[0]));r=x}else r={results:[],Ia:[],R:0};k.o.style.width=q+"px";for(q=u=0;r.Ia&&q<r.Ia.length;q++)
for(h=r.Ia[q],l=window.document.createElement("div"),l.className="rg_bb_layout",l.style.width=h.width+"px",l.style.height=h.height+"px",l.style.display="inline-block",k.o.appendChild(l),t=0;t<h.Ra;t++,u++)l.appendChild(k.ra[u].o);u=[];for(q=0;q<r.results.length;q++){var h=r.results[q],l=k.ra[q],t=l.o,v=h.width,B=h.height,x=l.o,z=x.getElementsByTagName("img")[0],w=l.width,D=l.height,w=v/B,E=_.R(l);!l.ra&&E<w||l.ra&&E>w?(w=Math.min(l.width,Math.floor(v)),D=Math.round(w/E)):(D=Math.min(l.height,Math.floor(B)),w=Math.round(D*E));var H=E=0,I=Math.round((v-w)/2),K=Math.round((B-D)/2);0>I&&(E=-1*_.ra(l,w-v),I=0);0>K&&(H=-1*_.qa(l,D-B));_.Q(x,{width:v+"px",height:B+"px"});_.Q(z,{width:w+"px",height:D+"px","padding-left":I+"px","margin-left":E+"px","margin-top":H+"px"});h.Ta||(p?t.style.marginLeft="1px":t.style.marginRight="1px");h.U||(t.style.marginBottom="1px");u.push(t)}
p=(y-r.R)/2;0<p&&(k.o.style.paddingTop=0+Math.ceil(p)+"px",k.o.style.paddingBottom=Math.floor(p)+"px");k=g==e.length-1&&f+
Ga<m;(f<m&&f+Ga>=m||k)&&window.google.log("facetscount","&visible="+(k?e.length:g)+"&total="+e.length+"&width="+m);f+=Ga}
window.document.getElementById("ifbc").style.display="";window.document.getElementById("ifbd").style.display="";c.insertBefore(a,d)}};}catch(e){_._DumpException(e)}})(this._ila);})();